### ISSUE TITLE
File names should scroll

### ISSUE THREAD

**Issue by hurley78** [prusa3d/Original-Prusa-MINI#10]
File names should scroll because PrusaSlicer makes long file names and it makes it difficult to pick the file you want to print.  You can't see the filament type or print time.  Should scroll like MK3S.

**Comment by 3d-gussner** [comment]
@hurley78 This is a firmware issue you should post in https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by 3d-gussner** [comment]
@hurley78 Can you please close the issue here?
![image](https://user-images.githubusercontent.com/25530011/78543839-89c25d80-77f9-11ea-9b62-dfb6d72ec795.png)
