### ISSUE TITLE
Stopping a print causes the printhead to crash into printed part.

### ISSUE THREAD

**Issue by HenrikPankoke** [prusa3d/Original-Prusa-MINI#11]
I had a print with 6 elements printing individual.
The elements is place like the photo. print is from back left to back right.
moving to front left to front right
![plate setup](https://user-images.githubusercontent.com/60976164/76214185-7f1da400-620c-11ea-970e-c08e3b3173f2.JPG)

When printing the front right element I stopped the print.
the printhead then moves backwards an into the element behind. causing this to be knocked of the plate. In this case it was a small part and not theat high adhesion. But larger parts with could adhesion could have damage that fan on the printhead. 
![crash](https://user-images.githubusercontent.com/60976164/76214463-14b93380-620d-11ea-9b7f-549ad3e2a4c0.JPG)

maybe changing stop command to move the nozzle up above highest printed element, before moving in any other direction. or just move nozzle clear of current print and stop movement.

**Comment by HenrikPankoke** [comment]
Sorry. created this the wrong place. Don't know how to delete.
Moved to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/257

**Comment by 3d-gussner** [comment]
@HenrikPankoke you find a `Close issue` button below ;-)
![image](https://user-images.githubusercontent.com/25530011/78543839-89c25d80-77f9-11ea-9b62-dfb6d72ec795.png)

**Comment by JohnnyDeer** [comment]
I´m closing this issue as duplicate.
