### ISSUE TITLE
feature request: support multiple steel sheets like the MK3

### ISSUE THREAD

**Issue by iandouglas** [prusa3d/Original-Prusa-MINI#12]
Would be awesome if the Mini's firmware allowed us to switch more easily between the smooth PEI and the textured PEI like the MK3 firmware.

**Comment by 3d-gussner** [comment]
Hi @iandouglas,

you posted the issue in the wrong repository. Please close it here and open it in https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by iandouglas** [comment]
thanks again @3d-gussner
