### ISSUE TITLE
feature request: holding in the knob to raise/lower Z like the MK3

### ISSUE THREAD

**Issue by iandouglas** [prusa3d/Original-Prusa-MINI#13]
I miss being able to hold in the knob and adjusting the Z height when the printer is otherwise idle. Could this be added as a firmware feature in the future?

**Comment by 3d-gussner** [comment]
Hi @iandouglas,

you posted the issue in the wrong repository. Please close it here and open it in https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by iandouglas** [comment]
thanks @3d-gussner

**Comment by 3d-gussner** [comment]
@iandouglas You are welcome
