### ISSUE TITLE
problem with ethernet mac adress

### ISSUE THREAD

**Issue by klimma1508** [prusa3d/Original-Prusa-MINI#14]
Hello, I wanted to connect the 3D printer Prusa MINI via cable to the Internet, but the mac address of the 3d printer has only 11 characters, even if it has 12 characters. Does Prusa MINI support the internet or is it a mistake? Thank you Klimš
![image](https://user-images.githubusercontent.com/55253868/78562421-9b1b6200-7819-11ea-9dce-26ac8ef3ec6b.png)

**Comment by bobc** [comment]
There is a zero missing, i.e. use "0a" instead of "a" : 109C 700A FEFF

But you should really submit an issue in the Buddy firmware repo.

**Comment by JohnnyDeer** [comment]
Hi @klimma1508 , this issue is related to firmware and have been already solved in version 4.0.5. I´ll close this issue.
