### ISSUE TITLE
Entering and exiting menu

### ISSUE THREAD

**Issue by geoper2** [prusa3d/Original-Prusa-MINI#16]
When jumping from a submenu back to the main menu, for example from Filament back to Main, the highlight goes back to the first item which is Print.
The same happens when editing values inside a submenu. Upon exit the highlight goes to the first item on the submenu. This is furstrating because you need to scroll through all of the menu items to get back to the item you were before.

It would be better for the user experience to keep the highlight in the same place that you were before exit or back. When exiting or going back the highlight needs to remain in the same item and not move to the first item on the screen.

**Comment by 3d-gussner** [comment]
@geoper2 As you have a firmware issue post this here: https://github.com/prusa3d/Prusa-Firmware-Buddy 
Please don't to forget to close this one.
