### ISSUE TITLE
Not a firmware issue - MINDA height

### ISSUE THREAD

**Issue by AndyThirtover** [prusa3d/Original-Prusa-MINI#2]
Dear Prusa

   My Mini was shipped with a lose MINDA.  It was not clear in the manual what the procedure for setting up the MINDA.  I got on to Tech Support and went with 1mm.

   So far my Mini does not have a perfect first layer for large prints - it is working though!

   I would like to be able to send jobs from my desk to the Mini which is in the basement.

   It would be useful to know progress of prints or be able to use OctoPrint.

   Overall, the finish is not quite as good as my 5000hr Mk3i3.

Regards

Andy

**Comment by JohnnyDeer** [comment]
Hi @AndyThirtover , let me summarize your issue... first part with MINDA was solved with help of our Tech Support. Second part will be possible trough Prusa Connect in future. And you can use OctoPrint on MINI already. 
First thing is about hardware and have been solved. Other suggestions are about firmware. So i´ll close this issue. You can crate feature request with your suggestion on Prusa-Firmware-Buddy. Thank you.
