### ISSUE TITLE
Scrolling name of print for mini ?

### ISSUE THREAD

**Issue by abosson** [prusa3d/Original-Prusa-MINI#22]
hello, I would suggest you  an improvement for the Mini ! 

the name of the print file is fixed and sometimes when you have to print the same part but with a différent material , the type of material is at the end of the name !

unfortunely, we can see it like on the MK3.

if it could be "scrolling" it could be great. 

I don't if it's possible with the new mainboard but it would be useful in my case (when you have the listing)

**Comment by JohnnyDeer** [comment]
Hi @abosson , this issue is related to Prusa-Firmware-Buddy and is duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/249 . I´ll close this one. Thank you for suggestion and understanding.
