### ISSUE TITLE
Feature request: Loading filament improvement.

### ISSUE THREAD

**Issue by nigeljohnson73** [prusa3d/Original-Prusa-MINI#23]
When you're loading, that step where it says click next to load, then gives you exactly zero seconds to ram filament in... well, it could turn the extruder stepper slowly to get the filament a catch, then clicking next would perform the load. That would be sooooo helpful.

**Comment by JohnnyDeer** [comment]
Hi @nigeljohnson73 , this is also related to firmware and is similar to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/260 . I'll close this one.
