### ISSUE TITLE
Feature request: Show last M117 message

### ISSUE THREAD

**Issue by nigeljohnson73** [prusa3d/Original-Prusa-MINI#27]
Yeah there is an option to look at all the messages, but it would be nice to see the last one on the screen somewhere just so you can watch the status as you run through your printer start code for example.

**Comment by JohnnyDeer** [comment]
Hi @nigeljohnson73 , this FR is related to firmware. Please create new one on Prusa-Firmware-Buddy following issue templates. I´ll close this one. Thank you for understanding.
