### ISSUE TITLE
Bug: Disconnecting "Remote Printer" does not return control to the Mini

### ISSUE THREAD

**Issue by nigeljohnson73** [prusa3d/Original-Prusa-MINI#29]
When you connect OctoPrint, you get the big logo. But, when you disconnect OctoPrint, the printer does not detect this and so you are forced to power cycle the printer to get control back. A workaround would be #28

**Comment by Gordontgopher** [comment]
You've opened a number of issues in the hardware repository. The developers are more likely if you raiser them in the firmware repository (https://github.com/prusa3d/Prusa-Firmware-Buddy)

**Comment by JohnnyDeer** [comment]
Hi @nigeljohnson73 , same as #28. I´m closing as duplicate.
