### ISSUE TITLE
STL and STEP Files don't open

### ISSUE THREAD

**Issue by 6ffm70** [prusa3d/Original-Prusa-MINI#3]
I'm having troubles opening the 3d files:
STL won't open in Prusaslicer; STEP won't open in two different professional CAD applications. I've also tried this on different computers to no avail.

**Comment by Strankler** [comment]
same here.

**Comment by 6ffm70** [comment]
I've got this resolved:
I opened the downloaded files with an editor, and the first line showed the <html opening tag. Repeat for all tested files - positive.

I've downloaded the files with Chromium, using #RMB #Save link on the file link in the repo. Well, it's not the file that is linked, but another page.

Issue corrected by cloning the repo.
