### ISSUE TITLE
Spool holder

### ISSUE THREAD

**Issue by okaerin** [prusa3d/Original-Prusa-MINI#30]
I want to print additional spool holder for my prusa mini. To do so I would need the required parts. Unfortunately I havent seen a part list. Is there one?

**Comment by EuphoricPenguin** [comment]
https://trello.com/b/IHnQ677R/part-list-bom

**Comment by pltaylor** [comment]
I know this is almost a year old, but I think this could be closed out now that the BOM is located here https://github.com/prusa3d/Original-Prusa-MINI/blob/master/BOM/SPOOLHOLDER.md
