### ISSUE TITLE
Multicolor print - unsuccessful load filament

### ISSUE THREAD

**Issue by Wolfram3D** [prusa3d/Original-Prusa-MINI#33]
When print of first color is done there is color changing phase. When load of new filament/color is successful everything is ok but when load is not successful (eg extruder doesn't grab the filament) there is no chance to repeat load filament - just question if color is ok.

Is possible to improve it like:
1) print of first color
2) color change phase -> 
   a) auto unload filament -> was filament successfully unloaded? When "Y" then press continue to load new filament. When "N" then repeat this step "unload filament".
   b) load filament -> was filament successfully loaded? When "Y" then purge and question if color is ok.... When "N" then repeat this step "filament loading".

Thanks

**Comment by JohnnyDeer** [comment]
Hi @Wolfram3D , you are in bad section. Your issue is related to Buddy firmware and this issue is solved in FW version 4.1.0-RC1, i'm closing this one.
