### ISSUE TITLE
Extruder rear piece. 

### ISSUE THREAD

**Issue by SgtKiLLx** [prusa3d/Original-Prusa-MINI#35]
So, I need to do a new extruder rear piece for my Mini.. and.. the bigger hole that the brass fitting piece twists into, with larger spaced threads , I attempted to get it screwed in, and the whole thing split.

**Comment by JohnnyDeer** [comment]
Hi @SgtKiLLx please contact our Support with this case. Chat in right down corner https://shop.prusa3d.com/en/ thank you.

**Comment by SgtKiLLx** [comment]
> Hi @SgtKiLLx please contact our Support with this case. Chat in right down corner https://shop.prusa3d.com/en/ thank you.

Prusa chat support doesn't know shit. I don't see how they can help with this. There is no way that this piece was heated up and threaded in.
