### ISSUE TITLE
Automatic skew correction.

### ISSUE THREAD

**Issue by riodoro1** [prusa3d/Original-Prusa-MINI#36]
Are there any plans to bring skew correction to the MINI? 
Ive noticed my printer is quite out of square (XY and YZ) and it’s not an uncommon problem on the internet.
Are the circles on the heat bed PCB actually there for this purpose and this would just need to be implemented in the code?

**Comment by JohnnyDeer** [comment]
Hi @riodoro1, this issue should be in Prusa-Firmware-Buddy repository and is related to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/385. I´m closing this one.
