### ISSUE TITLE
Bed heating up when unloading filament

### ISSUE THREAD

**Issue by hemdrup** [prusa3d/Original-Prusa-MINI#37]
Why does the bed heat up when unloading filament? (This is not when printing, but directly from the home menu)

Prusa Mini+ , version 4.2.1

 https://youtu.be/dRz50qD_JEE

**Comment by JohnnyDeer** [comment]
Hi @hemdrup, this issue should be in Prusa-Firmware-Buddy repository and its duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/706
I´m closing this issue.
