### ISSUE TITLE
Request pre heating 5-10sec to prevent failsafe in cold climates

### ISSUE THREAD

**Issue by boobslappy** [prusa3d/Original-Prusa-MINI#38]
I am requesting adding a 5-10 preheat to raise thermistors above threshold for those of us with our printing in cold areas. I’m having to use a blow dryer and don’t see why it couldn’t heat for a bit before checking thermistors. Could this feature be added? I’m on a prusa mini+. Thanks.

**Comment by TickTock-** [comment]
Yes.  Please!  (or lower the threshold)

**Comment by JohnnyDeer** [comment]
Hi @boobslappy this requirement should be in Prusa-Firmware-Buddy repository, please open it there according to the templates.  I´m closing this one here.
