### ISSUE TITLE
G CODE/M CODE PRO VYNECHÁNÍ BED LEVELING

### ISSUE THREAD

**Issue by kakafon2205** [prusa3d/Original-Prusa-MINI#39]
Ahoj
Mám dotaz, zda by do budoucna nešlo zakomponovat do sliceru nebo na spíš do rozhraní nějakého menu na tiskárně možnost vynechání mesh bed levelingu. Pořád dokola , nežli vychytám první vrstvu tak jsou průtahy s chladnutím , odměřováním rovinnosti a znovu nahřátím. Kdyby byla možnost to při prvním tisku nechat proměřit a po zjištění špatně vytištěné první vrstvy už pouštět program za tímto blokem. Nebo by to šlo překopat v sliceru vlastní hlavičku programu, ale mít pak možnost na tiskárně spustit program od určitého bloku. Takhle si musím upravovat program pro první spuštění a pak mít jiný pro následující opakování.

**Comment by JohnnyDeer** [comment]
Dobrý den @kakafon2205, prosím otevřete tento požadavek na funkci podle připravených šablon v repozitáři Prusa-Firmware-Buddy. Issue zde v hardwarové části uzavřu. Děkuji za pochopení
