### ISSUE TITLE
Filament run out sensor failing to pause print 

### ISSUE THREAD

**Issue by M8Harry** [prusa3d/Original-Prusa-MINI#40]
Had a print run out of filament but the mini kept printing.

The sensor has done this once in the past (older firmware version) but it has saved a print as well on the previous version.

Sucks seeing 4hrs of a 9hr print wasted because the printer didn't stop. When loading new flament I tested the sensor when it detected filament the filament the menu on screen updated and i pulled it out it changed back. So the sensor is working when not printing but it's hit and miss during prints. 
![IMG_20210105_204715](https://user-images.githubusercontent.com/30564050/103633336-b5958e00-4f99-11eb-85bd-4fb4b81d6955.jpg)

**Comment by JohnnyDeer** [comment]
Hi @M8Harry, with this issue please contact our Tech Support (chat is on right side down ... https://shop.prusa3d.com/en/ ).
