### ISSUE TITLE
Change Filament confirmation

### ISSUE THREAD

**Issue by Freland** [prusa3d/Original-Prusa-MINI#46]
When changing speed it it quite easy to press "Change Filament" in the menu. Which is quite annoying. An easy confirmation "Yes/No" would solve this "issue" easily.

**Comment by JohnnyDeer** [comment]
Hi @Freland, you are in wrong repository this is FW related and it´s duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1387. I´m closing this issue.
