### ISSUE TITLE
Feature request: show number of hours spent printing

### ISSUE THREAD

**Issue by DanidCH** [prusa3d/Original-Prusa-MINI#49]
As to help keep the printer well maintained I would appreciate having a menu entry allowing to have some statistics on how much time the Prusa Mini printer has spent printing. It would allow to check how fast you got to 100 hours tick.

**Comment by JohnnyDeer** [comment]
Hi @DanidCH, this request should be in firmware repository and there already exist https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/366. I´m closing this one as duplicate.
