### ISSUE TITLE
Please provide us a way to manually adjust the nozzle height

### ISSUE THREAD

**Issue by bhs67** [prusa3d/Original-Prusa-MINI#60]
For the Original Prusa Mini+ => As a customer request, please provide us a way to manually adjust the nozzle height (not part of a calibration).

**Comment by Prusa-Support** [comment]
Hi. You can do this using the First Layer Calibration (Calibrations menu) feature to adjust the Live Adjust Z value. 

I hope this helps you. But if this is not what you need, please contact our Technical Support Team.
https://help.prusa3d.com/article/customer-support_2287

Blas Palencia
Prusa Research
