### ISSUE TITLE
Create high contrast large text size screen mode for people with limited vision

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Original-Prusa-MINI#7]
Create high contrast large text size screen mode for people with limited vision

This would include research on how to create accessibility modes for the screen by looking at guidelines and talking to groups of people with limited vision.

This mode may also include making additional sounds on certain actions to keep the user informed to what the printer is doing.

**Comment by JohnnyDeer** [comment]
Hi @mrjohnc ,  this FR is related to firmware. Please create new one on Prusa-Firmware-Buddy following issue templates. I´ll close this one. Thank you for understanding.
