### ISSUE TITLE
Disabled heating on Prusa Mini leads to nozzle blockages

### ISSUE THREAD

**Issue by SeppeDR** [prusa3d/Original-Prusa-MINI#73]
Hi there,

I'm using the Prusa Mini for over 2 and a half years, but recently for mass production of parts, about 200 a day. This uses a lot of filament. As there is no automatic filament switching when the filament is finished, I often awake in the morning to the message that the heater has been disabled after 30 minutes of inactivity. 

This is a great feature, however, in those 30 minutes, my pla filament gets cooked in the nozzle. I have 4 high flow nozzles that have become completely useless as they are extremely difficult to clean and cold/warm pulls do not work on them. Needling is the only solution, however, risks of ruining the internal structure of the nozzle. That's about a 100 euros in the trash by now.

I wonder whether the 30 minutes of time is not excessive? It does not take long for the heater to reheat the nozzle to the right temperature. And if it would be switched off after a few minutes, I'm sure the pla wouldn't be cooked. 

Just letting it know, and hoping this could be perhaps changed if future firmware, or a setting for the user to choose.  Of course I know that there is some excellent solutions on my end as I could take more care to replenish the filament before it runs out, but that would mean a lot of spools with a little bit of filaments left or just a lot more work in general to make sure the nozzle is not getting blocked.

I had bad batches for over 2 weeks, with problems worsening. Took me a while to figure everything out. Could also help with less people having to contact Prusa support for clogged nozzles.

Anyways, thanks for reading. xx

**Comment by 3d-gussner** [comment]
@SeppeDR Please close this issue here and open it in https://github.com/prusa3d/Prusa-Firmware-Buddy firmware related github repository.

I am not sure if [`M86`](https://reprap.org/wiki/G-code#M86:_Set_Safety_Timeout)  is active on the Mini but you can try it to add this to your gcode files and PrusaSlicer profiles.
It has to be added to each gcode file as after reset or power on the default values are active again.
