### ISSUE TITLE
WiFi module support

### ISSUE THREAD

**Issue by rjkrause** [prusa3d/Original-Prusa-MINI#8]
I have a question about the WiFi module.  In ESP 01 is the default FW or some modified version?  Or in the current version of FW in Buddy Board is still not supported WiFi ?

**Comment by 3d-gussner** [comment]
@rjkrause This question should be asked in https://github.com/prusa3d/Prusa-Firmware-Buddy.

Please close the issue.

![image](https://user-images.githubusercontent.com/25530011/78543839-89c25d80-77f9-11ea-9b62-dfb6d72ec795.png)

**Comment by JohnnyDeer** [comment]
Hi @rjkrause , this issue is related to firmware and is duplicate. I´ll close this one.
